### ISSUE TITLE
Contact Us - Field label for the small letter "I" displayed as a Capital "I"

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Quicksilver-Chauffeur-Drive#33]
![image](https://cloud.githubusercontent.com/assets/12791909/11621123/dc8e9776-9cf3-11e5-92c8-6d7c25c1bc1b.png)

**Comment by Rahul-titan** [comment]
This issue is with font family "open_sansbold" only for this particular screen size. Letter showing is small letter.
